# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
    aarch64: ghcr.io/hassio-addons/debian-base:stable
    amd64: ghcr.io/hassio-addons/debian-base:stable
labels:
    org.opencontainers.image.title: "Home Assistant Add-on: OpenCode"
    org.opencontainers.image.description: "OpenCode web server add-on."
    org.opencontainers.image.source: "https://github.com/bradsjm/hassio-addons"
    org.opencontainers.image.licenses: "Apache License 2.0"
args:
    OPENCODE_VERSION: ""
