# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
args:
  MCPX_REF: main
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MCPX"
  org.opencontainers.image.description: "MCPX gateway and control plane add-on."
  org.opencontainers.image.source: "https://github.com/bradsjm/hassio-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
